### ISSUE TITLE
docs: convert documentation website to Storybook

### ISSUE THREAD

**Issue by LayZeeDK** [LayZeeDK/ngx-foundation-sites#52]
Use Storybook for documentation instead of the example app.

- [x] Convert example app components to Storybook stories #53
- [x] Migrate Cypress end-to-end tests from covering the example app to Storybook stories #58
- [x] Move example app styles to Storybook #59
- [x] Remove example app project #59
- [ ] [~~Migrate to Storybook 7~~](https://nx.dev/packages/storybook/documents/storybook-7-setup) (only available in Nx >=15.9)
